# SEO
title: Simaster Tutorials
author: Muhammad Yusuf
theme-name: Simaster Tutorials
generator: jekyll
keywords: scripts, education, files, githubpages, jekyll&hyde, adsense
logo: /assets/images/logo.png
baseurl: "/"
favicon:
paginate: 30
disqus: 'idtechannel'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

ganalytics: UA-113961478-1

facebook: https://www.facebook.com/profile.php?id=100093820787776
youtube: https://youtube.com/@idtechannel
github: https://github.com/mwnsofficial
whatsapp: https://wa.me/6287764241047
telegram: https://t.me/banjarstore
messenger: https://m.me/myarachma92
email: myarachma92@gmail.com

groups-facebook: https://m.facebook.com/groups/openclashpasswallindonesia
groups-whatsapp:
groups-telegram: https://t.me/idtechannel
groups-messenger: https://m.me/j/AbbDKvg3wXn3k-kX

# halaman bawaan simaster

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "infos"
    values:
      layout: "info"
      comments: true

# plugin simaster

plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
